apiVersion: apps/v1
kind: Deployment
metadata:
  name: releasechime
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: ghcr.io/slashnephy/releasechime
        name: releasechime
        envFrom:
          - configMapRef:
              name: releasechime-env
          - secretRef:
              name: releasechime-secret-env
        volumeMounts:
          - name: cache
            mountPath: /app/data
      volumes:
        - name: cache
          emptyDir: {}
