resources:
- deployment.yaml

commonLabels:
  app: "releasechime"

configMapGenerator:
- name: releasechime-env
  literals:
    - INTERVAL_SEC="600"
    - LOG_LEVEL="TRACE"
    - TARGET_RELEASE_REPOSITORIES="SlashNephy/saya"
    - TARGET_RELEASE_REPOSITORIES2="mirakc/mirakc"
    - TARGET_COMMIT_REPOSITORIES="DBCTRADO/TVTest"
    - TARGET_PATH_COMMIT_REPOSITORIES="l3tnun/EPGStation:v2,doc"

secretGenerator:
- name: releasechime-secret-env
  literals:
    - GITHUB_TOKEN="xxx"
    - DISCORD_WEBHOOK_URLS="https://discord.com/api/webhooks/xxx"
    - DISCORD_WEBHOOK_URLS2="https://discord.com/api/webhooks/xxx"
